version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretadminpassword
      POSTGRES_DB: ryker_vault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:supersecretadminpassword@db:5432/ryker_vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretadminpassword
      POSTGRES_DB: ryker_vault
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: testing
      AWS_SECRET_ACCESS_KEY: testing
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

volumes:
  pgdata:
