services:
  ryker-db:
    image: postgres:16-alpine
    container_name: ryker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ryker_vault
    ports:
      - "5432:5432"
    volumes:
      - ryker-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ryker_vault"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ryker-pgdata:
